# PI Background IP
# Copyright (c) 2026, Planet Innovation Pty Ltd
# 436 Elgar Rd, Box Hill, 3128, VIC, Australia
# Phone: +61 3 9945 7510
#
# The copyright to the computer program(s) herein is the property of
# Planet Innovation, Australia.
# The program(s) may be used and/or copied only with the written permission
# of Planet Innovation or in accordance with the terms and conditions
# stipulated in the agreement/contract under which the program(s) have been
# supplied.

variables:
  PROJECT_TAG: "aws-525-degraves"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - quality
  - test

image: ${CI_REGISTRY}/degraves/micropython_build_env_docker

checks:
  image: ${CI_REGISTRY}/degraves/ci/pre-commit-base:v1.0.0
  stage: quality
  tags: [$PROJECT_TAG]
  script:
    - pre-commit run --all-files --show-diff-on-failure

pi-project-compliance:
  stage: quality
  tags: [$PROJECT_TAG]
  variables:
    GIT_STRATEGY: none
  image:
    name: ${CI_REGISTRY}/pi-software/sqa/gitlab-config-compliance:latest
    entrypoint: [""]
  script:
    # Ensure you've created an Access Token in project settings called COMPLIANCE_CHECK with Maintainer role and just read_api permissions.
    # Copy the generated token into Settings > CI/CD > Variables with the key COMPLIANCE_CHECK, uncheck "Protect" and check "Mask" boxes.
    - check_compliance "${COMPLIANCE_CHECK}" "${CI_PROJECT_PATH}"
  artifacts:
    expire_in: 1 week
    paths:
      - output.xlsx

unit_test:
  image: ${CI_REGISTRY}/degraves/ci/micropython-unix-unittest:latest
  stage: test
  tags: [$PROJECT_TAG]
  needs: []
  script:
    - make tests
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - results/*.xml
